---
- name: Install CAs on OSG
  package:
    name: "{{ grid_ca_polices_pkgs.osg }}"
    state: latest
  when: grid_middleware == "OSG"

- name: Install CAs on UMD
  block:
    - name: Install CA policy packages for UMD
      package:
        name: "{{ grid_ca_polices_pkgs.umd }}"
        state: latest
    - name: Install wlcg-voms packages
      yum:
        name: "wlcg-voms-{{ item }}"
      with_items: "{{ grid_vos }}"
      ignore_errors: true
    - name: Install wlcg-iam-vomses packages
      yum:
        name: "wlcg-iam-vomses-{{ item }}"
      with_items: "{{ grid_vos }}"
      ignore_errors: true
    - name: Install wlcg-iam-lsc packages
      yum:
        name: "wlcg-iam-lsc-{{ item }}"
      with_items: "{{ grid_vos }}"
      ignore_errors: true
  when: grid_middleware == "UMD"
