---
# tasks file for hephyvienna.role-grid
- name: Configure Middleware repo
  include_tasks: repos.yml
  when: grid_enable_repo

- name: Configure certificates
  block:
    - name: Install ca_policy
      include_tasks: ca-policy.yml
      when: grid_enable_certificates != 'cvmfs'

    - name: Install fetch-crl
      include_tasks: fetch-crl.yml
      when: grid_enable_certificates != 'cvmfs'

    - name: Install empty CA policies
      include_tasks: empty-ca-policy.yml
      when: grid_enable_certificates == 'cvmfs'

    - name: Install host certificate
      include_tasks: hostcert.yml
      when: grid_host_certificate | length > 0

    - name: Install dummy hostcert
      include_tasks: dummy-hostcert.yml
      when: generate_grid_dummy_ca or generate_grid_dummy_host_certificate
  when: grid_enable_certificates
    
- name: Create Grid users
  block:
    - user:
        name: "{{ item }}"
        state: present
      loop: "{{ grid_users }}"
