---
- name: Install yum priorities
  package:
    name: yum-plugin-priorities
    state: present
  when: ansible_distribution_major_version == "7" 

- name: Install repository
  include_tasks: "{{ grid_middleware | lower }}.yml"

- name: Install WLCG repo RPM GPGKEY
  rpm_key:
    state: present
    key: https://linuxsoft.cern.ch/wlcg/RPM-GPG-KEY-wlcg
    validate_certs: false
- name: Install WLCG repo
  yum:
    name: "https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm"
    state: present
  when:
     - ansible_distribution_major_version == "9"
     - ansible_distribution == "AlmaLinux"

