---
dependency:
  name: galaxy
  # FIXME for MacOSX
  options:
    ignore-certs: true
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-'centos:7'}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    # FIXME: another workaround for python issue of molecule
    W: ignore::DeprecationWarning
    junit-xml: junit.xml
  lint:
    name: flake8
